### ISSUE TITLE
prometheus experimental UI fails because of credentials

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#595]
In the upper right corner there is an option to "Try experimental React UI".

Unfortunately this fails due to our credentials authentication model:

```
Error executing query: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /api/v1/query?query=go_goroutines&time=1575824134.128
```

<img width="716" alt="Screen Shot 2019-12-08 at 11 56 44 AM" src="https://user-images.githubusercontent.com/1085316/70392845-f0ea1580-19b1-11ea-8e11-53739c04561c.png">

**Comment by nkinkade** [comment]
It turns out that this error was the result of us using URLs with the basic http authorization credentials embedded in the URL (i.e., https://<user>:<pass>@domain.com). Even when using that apparently deprecated way of embedding basic auth credentials, the problem can be circumvented by simply loading the page again (not reloading as in ctrl-r, but reloading as putting the cursor in the address bar and hitting enter again. 

Additionally, this behavior seems unique Chrome ([which apparently is not even supposed to support embedded credentials in this way](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url)). When using Firefox, for example, the embedded-credential URLs work just fine when using the React UI link.

This issue is got around in two ways:
* Do no use URLs with embedded credentials (especially in Chrome)
* Use some sort of basic auth password manager (like [Multipass for Chrome](https://chrome.google.com/webstore/detail/multipass-for-http-basic/))
