### ISSUE TITLE
Grafana dashboard "k8s workload overview" double-counts some network traffic

### ISSUE THREAD

**Issue by pboothe** [m-lab/prometheus-support#625]
The daemonset flannel-platform seems to be newly in the dashboard and is using network bandwidth approximately equal to the total egress bandwidth on a host.  So if NDT is sending 130Mbps on a node, then flannel-platform reports that it is sending 134Mbps. on that same host.

**Comment by nkinkade** [comment]
Probably it needs to be excluded from the recording rule, since the flannel container runs with `hostNetwork=true`:

https://github.com/m-lab/k8s-support/blob/master/config/prometheus/rules.yml#L119

**Comment by nkinkade** [comment]
It also appears that metrics for the `flannel-platform` workload started showing up on Nov 14, which is coincident with [a k8s-support release](https://github.com/m-lab/k8s-support/releases/tag/v2.1.1) in which there were changes to the flannel DaemonSets assigning a new `workload` label to the DaemonSets:

https://github.com/m-lab/k8s-support/compare/v2.1.0...v2.1.1

Since our recording rules for those network metrics are querying on the `workload` label, this explains why this unwanted metric was not showing up before that date.  The fix will be to exclude it from the recording rule, since `hostNetwork=true` containers are not useful to monitor on this dashboard.
